pipeline {
  agent any

  options {
    ansiColor('xterm')
    disableConcurrentBuilds()
  }

  tools {
    nodejs 'NodeJS-12.16'
  }

  stages {
    stage('Install and clean') {
      steps {
        dir("${WORKSPACE}/client") {
          sh '''
            npm ci
            npm run clean
          '''
        }
      }
    }

    stage('Quality Assurance') {
      steps {
        dir("${WORKSPACE}/client") {
          sh '''
            npm run lint | true
            npm test
          '''
        }
      }
    }
  }
}
