version: '3.1'

services:
  mongo:
    image: mongo:4.2
    networks:
      - mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  mongodb:

volumes:
  mongodb-data:
