pipeline {
  agent any

  options {
    ansiColor('xterm')
    disableConcurrentBuilds()
  }

  tools {
    nodejs 'NodeJS-12.16'
  }

  stages {
    stage('Install and clean') {
      steps {
        dir("${WORKSPACE}/server") {
          sh '''
            npm ci
            npm run clean
          '''
        }
      }
    }

    stage('Quality Assurance') {
      parallel {
        stage('Static code analysis') {
          steps {
            dir("${WORKSPACE}/server") {
              sh '''
                npm run cpd | true
                npm run lint -- -f checkstyle > reports/eslint.xml | true
              '''
            }
          }
          post {
            always {
              recordIssues aggregatingResults: true, sourceCodeEncoding: 'UTF-8',
                referenceJobName: 'Dashboard/switchboard-server/1.x.x', tools: [
                  esLint(pattern: 'server/reports/eslint.xml'),
                  cpd(pattern: 'server/reports/cpd/jscpd-report.xml')
                ]
            }
          }
        }

        stage('Unit testing') {
          steps {
            dir("${WORKSPACE}/server") {
              sh '''
                npm test
              '''
            }
          }
          post {
            always {
              junit 'server/reports/junit.xml'
            }
            success {
              step([
                $class: 'CloverPublisher',
                cloverReportDir: 'server/reports/coverage',
                cloverReportFileName: 'clover.xml'
              ])
            }
          }
        }
      }
    }
  }
}
