pipeline {
  agent any

  tools {
    nodejs 'NodeJS-12.16'
  }

  stages {
    stage('Install and clean') {
      steps {
        dir("${WORKSPACE}/server") {
          sh '''
            npm ci
            npm run clean
          '''
        }
      }
    }

    stage('Quality Assurance') {
      steps {
        dir("${WORKSPACE}/server") {
          sh '''
            npm run lint | true
            npm test
          '''
        }
      }
    }
  }
}
